# Generated by Django 4.1.6 on 2023-03-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('birthday', models.DateField(help_text='Enter birthday in the following format: YYYY-MM-DD')),
                ('email', models.CharField(help_text='Enter your corporate email', max_length=100)),
                ('position', models.CharField(help_text='Your responsibilities', max_length=200)),
            ],
        ),
    ]
