# Generated by Django 4.1.6 on 2023-03-31 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diploma', '0003_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employer',
            name='birthday',
            field=models.DateField(help_text='Enter birthday in the following format: YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='email',
            field=models.CharField(help_text='Enter your corporate email', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='position',
            field=models.CharField(help_text='Your responsibilities', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='surname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
