# Generated by Django 4.1.6 on 2023-04-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0004_employer_date_created_employer_phone_employer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
