# Generated by Django 4.1.6 on 2023-04-18 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0006_pdf_files_delete_files_alter_employer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf_files',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdf_files',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
