# Generated by Django 4.1.6 on 2023-04-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0007_pdf_files_time_create_pdf_files_time_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf_files',
            old_name='pdf_file',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='pdf_files',
            name='topic',
            field=models.CharField(help_text='Тема документа', max_length=280),
        ),
    ]
