# Generated by Django 4.1.6 on 2023-04-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0008_rename_pdf_file_pdf_files_file_alter_pdf_files_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='files_doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Тема документа', max_length=280)),
                ('file', models.FileField(upload_to='document/pdf')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('categories', models.CharField(default='uncategorized', max_length=280)),
            ],
        ),
        migrations.DeleteModel(
            name='pdf_files',
        ),
    ]
