# Generated by Django 4.1.6 on 2023-04-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0009_files_doc_delete_pdf_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280)),
            ],
        ),
        migrations.DeleteModel(
            name='example',
        ),
        migrations.RenameField(
            model_name='files_doc',
            old_name='categories',
            new_name='category',
        ),
    ]
