# Generated by Django 4.1.6 on 2023-04-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0010_category_delete_example_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files_doc',
            name='date_confirm',
            field=models.CharField(help_text='Дата утверждения', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='files_doc',
            name='category',
            field=models.CharField(default='uncategorized', help_text='Категория', max_length=280),
        ),
    ]
