# Generated by Django 4.1.6 on 2023-05-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0011_files_doc_date_confirm_alter_files_doc_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='user',
        ),
        migrations.DeleteModel(
            name='files_doc',
        ),
        migrations.DeleteModel(
            name='employer',
        ),
    ]
