# Generated by Django 4.1.6 on 2023-05-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0014_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='files_doc',
            name='confirm',
            field=models.CharField(default='Не вступивший в силу документ', max_length=280, null=True),
        ),
    ]
