# Generated by Django 4.1.6 on 2023-05-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0015_confirm_files_doc_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files_doc',
            name='confirm',
            field=models.CharField(blank=True, default='Действующий документ', max_length=280),
        ),
    ]
