# Generated by Django 4.1.6 on 2023-06-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0017_remove_employer_position_alter_employer_birthday_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Confirm',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='user',
        ),
        migrations.DeleteModel(
            name='files_doc',
        ),
        migrations.DeleteModel(
            name='employer',
        ),
    ]
