# Generated by Django 4.1.6 on 2023-06-06 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0019_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Confirm',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='user',
        ),
        migrations.DeleteModel(
            name='files_doc',
        ),
        migrations.DeleteModel(
            name='employer',
        ),
    ]
